name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # or replace with your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or the Node version you're using

    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no your-username@your-server-ip << 'EOF'
          cd /var/www/freshcredit  # Navigate to your app's directory
          git pull origin main      # Pull the latest code
          npm install               # Install dependencies
          npm run build             # Build the app (if necessary)
          pm2 restart freshcredit-app  # Restart your app with PM2
        EOF
